### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by alifatico1** [perpetualKid/FreeTrainSimulator#133]
I run version 1.4.15-dev197 perfectly.

Only there is a script that doesn't work and in the New Year it does.

When I exit the program an error appears.

What should I do ?

Thanks and best regards.

Pedro (alifatico)
[error.txt](https://github.com/perpetualKid/FreeTrainSimulator/files/15177095/error.txt)

**Comment by perpetualKid** [comment]
this seems to be related to the Menu application - please provide more details what you are doing, what kind of script you may be running, and when this error occurs. Screenshots may be helpful as well

**Comment by alifatico1** [comment]
I send you the two captures.
In the first one with the New Year 151.2, when you press the F4 key on the right screen, what is seen on the left screen appears, information about the DPU system.
And when you press the F4 key, the text "Distributed Power" appears

In the second, no text appears on said key and it is not functional, so the image on the screen on the left does not change.
When you exit the program, the message "Interface not Registered" and the text that I already sent you appear.
Thanks and best regards.
Pedro

![dpu carlo](https://github.com/perpetualKid/FreeTrainSimulator/assets/120276327/ad76af27-90d0-4382-b3c2-84b33e700b3b)
![dpu kid](https://github.com/perpetualKid/FreeTrainSimulator/assets/120276327/840c2954-e655-4519-b1c3-5c899b2fcf26)

**Comment by perpetualKid** [comment]
is that rolling stock, and if any scripts, available somewhere for download and test?

**Comment by alifatico1** [comment]
These are the files that Carlo Santucci uploaded to Elvas Tower for the
operation of the dpu function.
I hope it helps you for the test.

Kind regards.

Pedro (alifatico)
 DPdemo_V31.zip
<https://drive.google.com/file/d/1PsSjSN6rZSu4nlwvhT3bh39w33VJFl1N/view?usp=drive_web>
 Instrucciones.txt
<https://drive.google.com/file/d/1oo-jZf7rsWMCO7TeZbiE-RoaMGO1KIbv/view?usp=drive_web>
 mlwgevo-12.zip
<https://drive.google.com/file/d/1bS5HNhdtLBwmUNtfys51E7XU5XpDc2HW/view?usp=drive_web>
 ortsevolutionseriescab.zip
<https://drive.google.com/file/d/1dSxE3Or8ErtRQ3MOwLkLDgAp16xxe-qR/view?usp=drive_web>
 svtxes44acset.zip
<https://drive.google.com/file/d/1KjlNiz4gOAW3HZSleafI6ugyLpaVClUx/view?usp=drive_web>

**Comment by perpetualKid** [comment]
Seems I don't have access to these files.

**Comment by alifatico1** [comment]
Try now

**Comment by perpetualKid** [comment]
that worked, thanks. 
I'll have a look, but as far I remember there are some changes that never were ported from ORNYMG
