### ISSUE TITLE
Error: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis'

### ISSUE THREAD

**Issue by actualindividual** [perpetualKid/FreeTrainSimulator#135]
Ever since the 1.4.16-dev.64 update got released, whenever I try to start a simulation, it gives me this error:

An essential file is missing and Free Train Simulator cannot continue.
'Microsoft.CodeAnalysis, Version=4.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. File not found.

This seems to be some kind of development dependency, where would one be able to download this? Log is also provided.
[OpenRailsLog.txt](https://github.com/user-attachments/files/16385782/OpenRailsLog.txt)

**Comment by perpetualKid** [comment]
looking into it, seems some issue with packaging

**Comment by perpetualKid** [comment]
should be fixed now in 1.4.16-dev.67
