### ISSUE TITLE
ActivityRunner crash on NullReferenceException

### ISSUE THREAD

**Issue by Zdendaki** [perpetualKid/FreeTrainSimulator#136]
I have installed Parsec virtual adapter that has `null` value in `AdapterRAM` property. That causes ActivityRunner to crash at line below. `System.NullReferenceException` is not catched and causes ActivityRunner to stop loading and exit game.
https://github.com/perpetualKid/FreeTrainSimulator/blob/229b23b729eb8343212262d497aedfb01962d9a2/Source/FreeTrainSimulator.Common/Info/SystemInfo.cs#L86

![Snímek obrazovky 2024-11-11 092949](https://github.com/user-attachments/assets/4a351715-0a65-4afa-9729-335992e8b710)
![Snímek obrazovky 2024-11-11 092906](https://github.com/user-attachments/assets/a5d9347d-994d-4189-b56d-350311a570a1)

**Comment by perpetualKid** [comment]
thanks for detailed bug report, that should be fixed shortly
