### ISSUE TITLE
Initiate Wiki to supplement documentation

### ISSUE THREAD

**Issue by perpetualKid** [perpetualKid/FreeTrainSimulator#45]

**Comment by HengYeDev** [comment]
do you plan to get the manual onto the wiki? i see that the manual pages are all in the repo

**Comment by perpetualKid** [comment]
> do you plan to get the manual onto the wiki? i see that the manual pages are all in the repo

I've been thinking about, but that would need some automated process both to import the docs first time, but also to keep in sync(one-way)/updated from upstream docs. At the moment this is not in scope from my end, but to use the wiki for any new documentation (in particular anything which differs from original OR). 

As always though, contributions are welcome!

**Comment by HengYeDev** [comment]
I also think that the docs may be too big for github wiki, i've never seen a github wiki with as much content as the documentation of OR. maybe we could setup readthedocs (since the docs are already in restructured-text

**Comment by HengYeDev** [comment]
I've just spun up a preview instance in my fork. https://hengyedev-orts-mg-docspreview.readthedocs.io/en/stable/

**Comment by HengYeDev** [comment]
Whooops sorry wrong link https://hengyedev-orts-mg-docspreview.readthedocs.io/en/manual/

**Comment by perpetualKid** [comment]
cool. how does it work, can this be integrated in CI/CD pipeline?

btw, OR itself also uses readthedocs to publish docs https://open-rails.readthedocs.io/en/latest/

**Comment by HengYeDev** [comment]
it's already CI. i.e. when i push anything to the docs it recompiles and reuploads

**Comment by perpetualKid** [comment]
just been reading a bit more in the readthedocs documentation today. I think just using RTD for the main manual is the better approach, but using the wiki as additional layer. Time may tell what's more appropriate.

On the other hand, there may also be a clear split - User documentation and manual using RTD, and developer documentation in the wiki/discussions. I think the current manual/docs in the repo are mostly targetting end users, while there is barely anything for developers.
