### ISSUE TITLE
accessibility for the blind in the stile of open bve

### ISSUE THREAD

**Issue by rings2006** [perpetualKid/FreeTrainSimulator#92]
so, i'm not a programer or know how the game is programed compared to openbve, but, all that would be needed to do, is get the tolk library, set it up with the game, and have things like the ability to narrate stations and signle distance, current speed and speed limit, and any other messages that are needed, also, menus like messing with signle points, if that is a thing, i'm not sure, but basicly, adding menu reading and station announsements as a start would be good, the main launcher is usible, so just ingame stuff is needed.

link to the tolk library https://github.com/dkager/tolk

**Comment by rings2006** [comment]
its been a wile, anything on this? can we like, work on it? not trying to sound rude, just wondering

**Comment by perpetualKid** [comment]
> its been a wile, anything on this? can we like, work on it? not trying to sound rude, just wondering

I'm not aware of any progress on that, but yes, anyone is welcome to work on this (or other items) and contribute.

**Comment by rings2006** [comment]
fair enough, i was wondering if you could please attempt working on it, i personally have no idea how to do it as i dont know how to code

**Comment by rings2006** [comment]
i'm also put how things should work here, so, for an example, lets say i move the accelerator or throttle or some other train controll, it should then narrate using tolk to use what ever screen reader what i have just done and what state the controll is in now. there should also be a sound that plays when i am close to a station indecating i must stop the train at that station. there should also be keyboard shortcuts to check some things like speed, how far the next station is, if the next signel is red or green or what ever. things like that, i'll explain more as time goes on or if i think of more ideas, and of course these dont have to all happen at once, just over time, as it does seem to be a big project as far as i can tell
